name: Test Anchor Behavior

on:
  workflow_dispatch:
    inputs:
      test:
        description: "A string!"
        default: "Sample text"
        required: false
        type: "string"

jobs:
  test1:
    runs-on: "ubuntu-latest"
    steps:
      - &test-anchor1
        name: Test1
        run: &test-anchor2 |
          echo "Hello world"
          echo "${{ inputs.test }}"

  test2:
    runs-on: "ubuntu-latest"
    steps:
      - *test-anchor1
      - name: Test2
        run: *test-anchor2
